Repository dmarts05/pixelgram, pull requests merged in 2025-05, with the labels that each got.

#35 Feat/add-pixelart-publishing
  backend/pixelgram/__main__.py
  backend/pixelgram/models/post.py
  backend/pixelgram/models/user.py
  backend/pixelgram/routers/posts.py
  backend/pixelgram/schemas/post.py
  backend/pixelgram/services/supabase_client.py
  backend/pixelgram/settings.py
  backend/tests/test_caption.py
  backend/tests/test_posts.py
  backend/tests/utils.py
  frontend/src/components/PublishPixelartModal.tsx
Labels: enhancement

#37 Add feed page
  backend/pixelgram/models/post.py
  backend/pixelgram/models/user.py
  backend/pixelgram/routers/captions.py
  backend/pixelgram/routers/posts.py
  backend/pixelgram/schemas/camel_model.py
  backend/pixelgram/schemas/post.py
  backend/pixelgram/services/__init__.py
  backend/pixelgram/services/hf_client.py
  backend/pixelgram/services/supabase_client.py
  backend/pixelgram/settings.py
  backend/pixelgram/utils/__init__.py
  backend/pixelgram/utils/constants.py
  backend/pytest.ini
  backend/tests/conftest.py
  backend/tests/overrides.py
  backend/tests/test_captions.py
  backend/tests/test_main.py
  backend/tests/test_posts.py
  backend/tests/utils.py
  frontend/bun.lock
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/hero.webp
  frontend/src/components/BrandLogo.tsx
  frontend/src/components/NavLinks.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/forms/InputField.tsx
  frontend/src/components/forms/LogInForm.tsx
  frontend/src/components/forms/PublishPixelartModal.tsx
  frontend/src/components/forms/SignUpForm.tsx
  frontend/src/components/navbar/AuthMenu.tsx
  frontend/src/components/navbar/DesktopMenu.tsx
  frontend/src/components/navbar/MenuLinks.tsx
  frontend/src/components/navbar/MobileMenu.tsx
  frontend/src/components/navbar/Navbar.tsx
  frontend/src/components/post-card/PostCard.tsx
  frontend/src/components/post-card/PostCardActions.tsx
  frontend/src/components/post-card/PostCardDescription.tsx
  frontend/src/components/post-card/PostCardHeader.tsx
  frontend/src/components/post-card/PostCardImage.tsx
  frontend/src/components/post-card/PostCardTimestamp.tsx
  frontend/src/layouts/Layout.tsx
  frontend/src/pages/CanvasPage.tsx
  frontend/src/pages/FeedPage.tsx
  frontend/src/pages/LogInPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/services/auth-service.ts
  frontend/src/services/fetch-api.ts
  frontend/src/services/posts-service.ts
  frontend/src/types/link.ts
  frontend/src/types/post.ts
  frontend/src/utils/constants.ts
Labels: enhancement

#44 Fix non square images in feed
  frontend/src/App.tsx
  frontend/src/components/AuthenticatedRoute.tsx
  frontend/src/components/InfiniteScrollIntersectionObserver.tsx
  frontend/src/components/UnauthenticatedRoute.tsx
  frontend/src/components/post-card/PostCard.tsx
  frontend/src/components/post-card/PostCardImage.tsx
  frontend/src/pages/FeedPage.tsx
Labels: bug

#48 Add frontend CI
  .github/workflows/backend-ci.yml
  .github/workflows/frontend-ci.yml
  backend/Dockerfile
  backend/pixelgram/services/hf_client.py
  backend/requirements.txt
  frontend/package.json
Labels: enhancement

#59 Feat/saved posts window
  backend/pixelgram/models/__init__.py
  backend/pixelgram/models/post.py
  backend/pixelgram/models/post_saved.py
  backend/pixelgram/models/user.py
  backend/pixelgram/routers/posts.py
  backend/pixelgram/schemas/post.py
  backend/tests/test_posts.py
  frontend/src/App.tsx
  frontend/src/components/post-card/PostCard.tsx
  frontend/src/components/post-card/actions/PostCardActions.tsx
  frontend/src/components/post-card/actions/SaveButton.tsx
  frontend/src/pages/account/SavedPostsPage.tsx
  frontend/src/services/posts-service.ts
  frontend/src/types/post.ts
Labels: enhancement

#75 Refactor/fetch to mutation
  frontend/src/components/forms/PublishPixelartModal.tsx
  frontend/src/services/posts-service.ts
Labels: enhancement

#76 fix: adapt style of landing page to narrow screens
  frontend/src/components/navbar/Navbar.tsx
Labels: enhancement

#81 Fix/state multicolor
  frontend/src/components/canvas/toolbox/Toolbox.tsx
  frontend/src/components/canvas/toolbox/ToolboxColorButton.tsx
  frontend/src/components/canvas/toolbox/ToolboxColorPicker.tsx
  frontend/src/pages/CanvasPage.tsx
  frontend/src/types/tool.ts
Labels: bug

#82 Feat/canvas cursor
  frontend/src/components/canvas/Canvas.tsx
Labels: enhancement

#83 fix: implement local state management for posts in PostsGrid component
  frontend/src/components/PostsGrid.tsx
Labels: bug

#85 Fix dependabot vulnerability
  backend/pyproject.toml
  backend/uv.lock
  frontend/bun.lock
  frontend/package.json
Labels: bug

#93 Doc/write readme
  README.md
Labels: documentation
